### ISSUE TITLE
[Question] Storage model mapping to OpenEHR Clinical Document

### ISSUE THREAD

**Issue by gayanper** [ppazos/cabolabs-ehrserver#1058]
Do you have any documentation describing how the storage tables are mapped to openehr documents ? i would like to understand how to query data directly from the database if possible.

**Comment by ppazos** [comment]
@gayanper this system is designed as a microservice, the database should never be queried directly, because it misses all internal structures, rules, processes and checks. The class to table mapping is the standard Grails mapping. The closest you can get is to query using the Grails GORM. How EHRServer was designed is to use the API and the path-based queries (https://docs.google.com/document/d/1pGJXIWHCgjyiofLmNHRTG7UFuB-tVWzm625X5rkiHiw/edit?usp=sharing) to get data from the server.

If you have further questions, please use our support channel https://gitter.im/CaboLabs/EHRServer
