### ISSUE TITLE
Test data is not realistic

### ISSUE THREAD

**Issue by samheard** [ppazos/cabolabs-ehrserver#112]
I would suggest that we get a few scenarios together with realistic data. Even changing the data in Pablo's record so that the diastolic and systolic values are 74 mmHg and 128 mmHg respectively would help (Systolic > Diastolic by 40 or so mmHg - Systolic 100-230, Diastolic 60-120).

Happy to edit the data if you show me how.

**Comment by ppazos** [comment]
There is another project in my repos, the EHRCommitter, that generates composition data randomly based on an OPT.
Current data en EHRServer will be erased in order to deploy a couple of new features.
What I can do is put an instance of EHRCommitter and EMRApp on the cloud. Those can be used to send compositions to the EHRServer also on the cloud.
It would be great if you can use those apps to generate a couple of more realistic compos. I can backup those to not lose them in the next updates.
What do you think?

**Comment by ppazos** [comment]
@samheard we have this to generate data: http://committer-ehrserver.rhcloud.com/committer

You can login with your EHRServer account. You can create one from: https://cabolabs-ehrserver.rhcloud.com/ehr/
