### ISSUE TITLE
It's possible with another database?

### ISSUE THREAD

**Issue by JDSBCC** [ppazos/cabolabs-ehrserver#395]
Hi again,
Now that I finish my app, I'm looking for different ways of implementing it. In order to use the technology of the company i need to work with a different database. So, my question is: is it possible to run EHRServer with PL/SQL or another database? if this is possible,  will I need to modify some file in addiction to DataSource.groovy?

Thanks

**Comment by ppazos** [comment]
@JDSBCC totally. That is a Grails feature. This might help (it's a little old) http://vidorsolutions.blogspot.com.uy/2011/01/use-postgresql-within-your-grails.html

Because of reserved words on each DB brand, you might need to update the mappings on domain classes to change column names: http://stackoverflow.com/questions/10482328/how-to-map-domain-object-properties-to-columns

For relational databases that is all what I think you need. For no-SQL databases you might need to look at: https://grails.org/plugins/tag/nosql
