### ISSUE TITLE
allow me to delete templates from server.

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/cabolabs-ehrserver#871]
Actually we want to delete some templates from our organisation, and no such option is showing in our account.

**Comment by saurabhrasp** [comment]
Pablo,
Please suggest how we can delete some dummy templates from our account?
If currently this feature is not present and will available in future then please delete these below template uids so that we can upload some more templates as per our needs.

a72d7738-afd5-4ce1-a587-799e0ffc92d4
854c2491-5d2b-4866-8a46-b599bdb69cad
672ca227-4b34-4d9f-9db4-23aede2223e0
9fd9ced3-a240-470d-87b0-37930de7051b

**Comment by ppazos** [comment]
@saurabhrasp OPT delete is an admin feature. The problem of deleting OPTs is that queries using paths from those OPTs can generate problems while editing them since some paths might not exist any more. Another issue that deleting OPTs will generate is failing on indexing new compositions compliant with those OPTs.

Before opening the delete feature for OPTs, I need to implement checks to allow notifying the user on those issues before deleting. This implies doing some checks that are not trivial.

Tomorrow I'll delete those OPTs for you and will try to check the conditions to enable OPT deletion ASAP.

**Comment by saurabhrasp** [comment]
Pablo, can you delete any opt just for some time actually i need to test one thing urgently regarding multimedia type.

**Comment by ppazos** [comment]
@saurabhrasp done on #919
