### ISSUE TITLE
Recently we are facing issue while posting composition into ehrserver

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/cabolabs-ehrserver#874]
`<result>
 <type>AR</type>
 <message>Bad content, could not process committed compositions dateString is null</message>
 <code>EHR_SERVER::API::RESPONSE_CODES::468</code>
</result>
`

**Comment by saurabhrasp** [comment]
[MentalCarePlan_Composition.zip](https://github.com/ppazos/cabolabs-ehrserver/files/1779643/MentalCarePlan_Composition.zip)

Pablo find the attached composition for Mental Health Care Plan.

**Comment by ppazos** [comment]
@saurabhrasp try to add a context element after the composer, like this:

```
<composer xsi:type="PARTY_IDENTIFIED">
      <name>Dr. Pablo Pazos</name>
    </composer>
    <context>
      <start_time>
        <value>{% now 'iso-8601', '' %}</value>
      </start_time>
      <setting>
        <value>Hospital Montevideo</value>
        <defining_code>
          <terminology_id>
            <value>openehr</value>
          </terminology_id>
          <code_string>229</code_string>
        </defining_code>
      </setting>
    </context>
```

The issue is happening because EHRServer considers the context is mandatory for event compositions. Since it is missing, it tries to access the stat_time and fails.

I need to return a more understandable error message.

**Comment by saurabhrasp** [comment]
Pablo,
But before committing this xml instance i used to commit some other instances successfully and those xml don't have context section after composer.

**Comment by ppazos** [comment]
@saurabhrasp openEHR hast two types of compositions, event and persistent. For persistent, context is not needed since those work as versionable singleton documents inside the EHR, for instance the problem list on a problem oriented record, is unique inside the EHR, but a doctor can add, remove or change status of the health problems in the list.

With event, we need the context, since the event happens at a specific time or time frame.

If you have other event compos that are accepted by the EHRServer, please attach them to check why those are working. But looking at the code, it always checks for context.start_time for event compositions. If that is not present, the null datestring exception will be thrown.

**Comment by ppazos** [comment]
@saurabhrasp I detected opt ingen version is not generating the context, maybe your are using that to generate test instances, I'll fix it.
