### ISSUE TITLE
Errors thrown for XmlUtil.serialize

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#94]
| Error Warning: org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
| Error Warning: org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
| Error Warning: org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognize
d.

Thrown by XmlUtil.serialize when the XMLs are saved to disc on the commit action of RestController.
Seems to be an error in Groovy/Java not in the server.

**Comment by ppazos** [comment]
The SaxParser implementation used in Groovy is the Xerces one, so the problem is in Xerces.

Here it says to update the Xerces implementation to xercesImpl 2.9.1

http://stackoverflow.com/questions/20473689/org-xml-sax-saxnotrecognizedexception-feature-http-javax-xml-xmlconstants-fe

**Comment by ppazos** [comment]
Tried to add a dependency to a newer version of xercesImpl but it didn't work:
BuildConfig:
compile 'xerces:xercesImpl:2.11.0'

Got the same warnings and:

Error |Warning: validation was turned on but an org.xml.sax.ErrorHandler was not
Error |set, which is probably not what is desired.  Parser will use a default
Error |ErrorHandler to print the first 10 errors.  Please call
Error |the 'setErrorHandler' method to fix this.
Error |Error: URI=null Line=1: Document root element "data", must match DOCTYPE root "null".
Error |Error: URI=null Line=1: Document is invalid: no grammar found.

**Comment by ppazos** [comment]
Other SAX implementations http://www.edankert.com/apis/sax.implementations.html

More links:
http://stackoverflow.com/questions/11677572/dealing-with-xerces-hell-in-java-maven
http://docstore.mik.ua/orelly/xml/xmlnut/ch25_03.htm
http://www.journaldev.com/1198/java-sax-parser-example-tutorial-to-parse-xml-to-list-of-objects
http://sax.sourceforge.net/?selected=get-set
http://stackoverflow.com/questions/9977418/parsing-very-large-xml-files-with-xmlslurper
http://stackoverflow.com/questions/7080401/groovy-nekohtml-sax-parser
http://docs.groovy-lang.org/latest/html/api/groovy/xml/XmlUtil.html#newSAXParser(java.lang.String,%20boolean,%20boolean,%20java.io.File)

**Comment by edgarze188** [comment]
Pablo Pazos good, have problems of: XmlUtil.serialize

I am using: xercesImpl: 2.11.0 (this version is the pusistes on github and does not work me)
And update that version and Use other versions, XercesImpl link:
2.11.0
http://www.java2s.com/Code/Jar/x/Downloadxercesimpl2110sourcesjar.htm
http://www.java2s.com/Code/Jar/x/Downloadxercesxercesimpl211jar.htm
2.9.1
http://www.java2s.com/Code/Jar/x/DownloadxercesImpl291sourcesjar.htm
I can use that jar
I still leaving themselves essage 3 above, you recommend me
I have a Linux server should
1GB of Ram, who recommended me to put those values (increase RAM, that's why I did not create the .xml file) is why we get:
Error 500: Internal Server Error

I put it like this:
Xmx512M
Xms256M
XX: PermSize = 256m
XX: MaxPermSize = 300m

**Comment by ppazos** [comment]
@edgarze188 what are you trying to serialize? Remember those are just warnings no errors.

**Comment by edgarze188** [comment]
Thanks Pablo, but does not generate the ".XML"
I'm using OpenJDK 1.7.0_79 ; Grails 2.4.4 ; xercesImpl: 2.11.0
You could see the images
first console: EMR
second console: EHRserver

I commit and generates multiple server is disconnected, and an average of 25 times and repeats, EHRServer contributions out repeated the same records, but does not locate the ".XML" because I do not think

![1](https://cloud.githubusercontent.com/assets/13157454/9011790/47fa599e-3775-11e5-903b-776360aa44c0.png)
![2](https://cloud.githubusercontent.com/assets/13157454/9011791/48096a9c-3775-11e5-8b89-84c5d9265687.png)
![3](https://cloud.githubusercontent.com/assets/13157454/9011792/4812ed74-3775-11e5-8c2a-250ac8740117.png)
![4](https://cloud.githubusercontent.com/assets/13157454/9011793/481ee994-3775-11e5-84ee-7591239044cf.png)
![5](https://cloud.githubusercontent.com/assets/13157454/9011794/482d5f10-3775-11e5-9a66-2928e9c119d4.png)

Thanks

**Comment by ppazos** [comment]
The problem is in your 3rd image: the error is FileNotFound.

You should have a /compositions and /versions folder in your system with write permissions.

See the Config.groovy file for the paths, you can change them.

**Comment by edgarze188** [comment]
Thank you, that was my error, create 2 folder you said me and otorge them all permits, already running.
Greets and a hug.
![1](https://cloud.githubusercontent.com/assets/13157454/9020184/7d4de5d6-37c3-11e5-98cd-c233299e9a4e.png)
![2](https://cloud.githubusercontent.com/assets/13157454/9020185/7d59830a-37c3-11e5-89ce-5af3dda919bf.png)

**Comment by ppazos** [comment]
Done! thanks to @jagedn
